### ISSUE TITLE
Custom Wordlists: text format support

### ISSUE THREAD

**Issue by antoninoLorenzo** [camandel/check-password-strength#34]
Hi, I came across `check-password-strength` and I wanted to see how it worked; I noticed that custom wordlists (`--customdict`) supports only JSON files, however for some use cases (really long wordlists) it would be easier supporting classic text file wordlists (`.txt` or `.lst`).

It would be something like this:
```golang
import (
        ...
	"slices",
	"path/filepath",
)
...

func loadCustomDict(filename string) ([]string, error) {

	var customDict []string
	var d jsonData

	log.Debugf("custom dict filename: %s", filename)

	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()

        // os instead of ioutils
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}

        // check file type by extension
        ext := filepath.Ext(filename)
	if !slices.Contains(SUPPORTED, ext) {
		panic(fmt.Sprintf("%s not supported\n", ext))
	}

	if ext == "json" {
		err = json.Unmarshal(data, &d)
		if err != nil {
			return nil, err
		} 
                if len(d.Words) == 0 {
			return nil, errors.New("Object 'words' is empty, custom dictionary not loaded")
		}
                customDict = append(customDict, []string{d.Words...})
	} else {
		customDict = append(customDict, strings.Split(string(data), "\n"))
	}

	return customDict, nil
}
```

> Note: I changed `ioutil.ReadFile` to `os.ReadFile` because the first one is marked as deprecated [there](https://pkg.go.dev/io/ioutil).

I hope this change makes sense to you, however if it isn't the case I would like to know the reason to support only JSON files.

**Comment by camandel** [comment]
It's a good idea, I'll include your changes in the next days. Thanks!
